import { useState, useRef } from "react";
import VideoCard from "./components/videocard";

// ==========================================
// 1. DATA
// ==========================================
const SECTIONS = [
  {
    id: "king-of-meat",
    label: "King of Meat",
    intro: "My work for King of Meat project. Audio and tech described in short videos",
    videos: [
      { title: "Music system for multiplayer with UGC", video: "https://www.youtube.com/embed/ZQqCkzDb6kI", description: "The unique challenge lay in the game's format: it's a networked multiplayer title with robust User-Generated Content (UGC) capabilities. The system couldn't rely on pre-scripted triggers. Instead, it had to analyze player actions in real-time and adapt to any user-created level, no matter how chaotic or unconventional.\n\nThe video below offers a brief overview of the implementation in Wwise." },
      { title: "Procgen music bed for shop atmosphere", video: "https://www.youtube.com/embed/FLcrB9zjiYk", description: "No need for long ambiance loops to create non-repetitive background music. An interesting idea for how to stitch one-shots and pauses into a procedural percussive loop in Wwise. Add a couple of drones and you've got a background bed that never repeats." },
      { title: "Dynamic crowd system. Wwise implementation.", video: "https://www.youtube.com/embed/01GdKjrN8M8", description: "It's about the dynamic crowd reactions system, designed to deliver an authentic, high-energy TV show atmosphere. The system is fully responsive and tightly integrated with real-time player actions." },
    ],
  },
  {
    id: "factorio",
    label: "Factorio",
    intro: "Sound designer & composer for games and interactive media. Focused on creating high-quality audio experiences.",
    videos: [
      { title: "Factorio Enemies Sound Design", video: "https://www.youtube.com/embed/XDVa0ihX10Q", description: "Descriptive video of enemies audio creation" },
      { title: "Factorio Combat Robots Sound Design", video: "https://www.youtube.com/embed/JC2ppfKRRNI", description: "Example description." },
      { title: "Factorio Flying Robots sounds", video: "https://www.youtube.com/embed/AJiDw4c9RIY", description: "Example description." },
    ],
  },
  {
    id: "redesigns",
    label: "Redesigns",
    intro: "Some are driven by pure curiosity and fun, others are conceptual solutions for specific design challenges.",
    videos: [
      { title: "Some redesigns", video: "https://www.youtube.com/embed/TQtxutZEYL4", description: "Full audio replacement." },
      { title: "Some redesigns", video: "https://www.youtube.com/embed/SM2TirBNuDs", description: "Full audio replacement." },
    ],
  },
  {
    id: "advertising",
    label: "Advertising",
    intro: "Commercial and promotional sound design. Delivering clear, punchy, and broadcast-ready audio mixes.",
    videos: [
      { title: "Syngenta Commercial Spot. SFX + Mixing", video: "https://youtube.com/embed/7ltd8OzdoUM", description: "Full audio replacement for the video, including sound design, voiceover processing, and final mix." },
      { title: "Esse Commercial Spot. SFX + Mixing", video: "https://youtube.com/embed/BbZFDiv3vcw", description: "A short commercial spot featuring intimate, ASMR-focused sound design." },
    ],
  },
  {
    id: "music",
    label: "Music",
    intro: "Bridging the gap between cinematic media and club culture: electronic music for trailers, games, and live acts.",
    videos: [
      { title: "Spring Spirit", video: "https://www.youtube.com/embed/6023ImFR3RM", description: "A piece I composed after being deeply moved by the film I Origin." },
      { title: "Forest Story", video: "https://www.youtube.com/embed/lJ6JMFQ95LA", description: "Music created for an unannounced project. The video was generated by AI, inspired by the story by Sterling Lanier." },
      { title: "Factorio Launch", video: "https://www.youtube.com/embed/qObuy_yCIdg", description: "Music for Factorio launch trailer." },
    ],
  },
];

const NAV = SECTIONS.map(s => ({ id: s.id, label: s.label }));

// ==========================================
// 2. COMPONENTS
// ==========================================
const Background = () => {
  const generate = (phase, amp, y) => {
    let path = "";
    for (let x = -100; x <= 2200; x += 40) {
      const envelope = Math.sin(((x + 100) / 2300) * Math.PI);
      const yy = Math.sin((x + phase) / 120) * amp * envelope + y;
      path += `${x === -100 ? 'M' : 'L'} ${x} ${yy} `;
    }
    return path;
  };

  return (
    <div className="fixed inset-0 -z-10 overflow-hidden bg-[#0a0705]">
      <div className="absolute inset-0 bg-gradient-to-br from-[#0f0a08] via-[#1a110d] to-[#241712]" />
      <svg className="absolute inset-0 w-full h-full" preserveAspectRatio="none">
        <defs>
          <filter id="glow">
            <feGaussianBlur stdDeviation="4" result="blur" />
          </filter>
        </defs>
        {Array.from({ length: 45 }).map((_, i) => {
          const d = generate(i * 45, 35 + i * 2, 80 + i * 28);
          const alpha = 0.15 + i * 0.01;
          return (
            <g key={i}>
              <path d={d} stroke={`rgba(59,130,246,${alpha * 0.6})`} strokeWidth={6} fill="none" filter="url(#glow)" />
              <path d={d} stroke={`rgba(59,130,246,${alpha})`} strokeWidth={1.5} fill="none" />
            </g>
          );
        })}
      </svg>
      <div className="absolute inset-0 bg-[radial-gradient(circle_at_center,transparent_0%,#0a0705_90%)]" />
    </div>
  );
};

// ==========================================
// 3. MAIN
// ==========================================
export default function Portfolio() {
  const [isOpen, setIsOpen] = useState(false);
  const [page, setPage] = useState<"home" | "about">("home");
  const [activeVideo, setActiveVideo] = useState<string | null>(null);
  const playerRef = useRef({});

  const scrollTo = (id) => {
    document.getElementById(id)?.scrollIntoView({ behavior: "smooth" });
    setIsOpen(false);
  };

  const goHome = () => {
    setPage("home");
    setIsOpen(false);
    window.scrollTo({ top: 0, behavior: "smooth" });
  };

  const goAbout = () => {
    setPage("about");
    setIsOpen(false);
    window.scrollTo({ top: 0, behavior: "smooth" });
  };

  const playVideo = (video) => {
    Object.values(playerRef.current).forEach(p => {
      if (p && p.stopVideo) p.stopVideo();
    });
    setActiveVideo(video);
  };

  return (
    <div className="relative min-h-screen text-white font-sans">
      <Background />

      {/* ===== ШАПКА (sticky) ===== */}
      <header className="sticky top-0 z-50" style={{ boxShadow: "0 24px 48px -12px rgba(0,0,0,0.7)" }}>
        {/* Коричневый блок */}
        <div className="h-40 bg-gradient-to-r from-[#1c120d] to-[#2b1a13] border-b border-white/5">
          <button
            onClick={() => setIsOpen(!isOpen)}
            className="absolute right-6 top-3 text-gray-400 hover:text-white focus:outline-none md:hidden"
            aria-label="Toggle menu"
          >
            {isOpen ? (
              <svg className="w-7 h-7" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M6 18L18 6M6 6l12 12" />
              </svg>
            ) : (
              <svg className="w-7 h-7" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M4 6h16M4 12h16M4 18h16" />
              </svg>
            )}
          </button>
        </div>

        {/* Аватар + имя + About */}
       <div className="relative flex items-end justify-between px-8 -mt-16 pb-1 bg-[#0a0705]">
          <div className="flex items-end gap-5">
            <button onClick={goHome} className="cursor-pointer" title="Go home">
              <div className="w-32 h-32 rounded-2xl bg-gray-500 border-4 border-[#0a0705] shadow-2xl overflow-hidden shrink-0">
                <img src="/avatar.jpeg" alt="Val Sol" className="w-full h-full object-cover" />
              </div>
            </button>
            <button onClick={goHome} className="cursor-pointer pb-2 text-left">
              <h1 className="text-3xl font-bold tracking-tight text-white drop-shadow-md">Val Sol</h1>
              <p className="text-blue-400 text-base font-medium drop-shadow-md">Sound Designer / Composer</p>
            </button>
          </div>
          <button
            onClick={goAbout}
            className={`pb-3 text-sm transition-colors ${
              page === "about" ? "text-blue-400 font-medium" : "text-gray-400 hover:text-white"
            }`}
          >
            About
          </button>
        </div>

        {/* Градиент: контент уходит под шапку */}
      

        {/* Мобильное меню */}
        {isOpen && (
          <div className="md:hidden bg-[#0a0705] border-t border-white/5">
            <div className="flex flex-col px-8 py-4 space-y-3">
              <button
                onClick={goAbout}
                className="text-lg text-gray-300 hover:text-white transition-colors py-1 text-left"
              >
                About
              </button>
              {NAV.map(item => (
                <button
                  key={item.id}
                  onClick={() => { goHome(); setTimeout(() => scrollTo(item.id), 100); }}
                  className="text-lg text-gray-300 hover:text-white transition-colors py-1 text-left"
                >
                  {item.label}
                </button>
              ))}
            </div>
          </div>
        )}
      </header>

      {/* ===== КОНТЕНТ ===== */}
      <main className="relative z-10 pt-8">
        {page === "about" ? (
          <section className="min-h-screen flex items-center">
            <div className="p-10 max-w-3xl mx-auto">
              <h2 className="text-4xl font-bold mb-6">About Me</h2>
              <p className="text-gray-400 text-lg font-medium mb-6">
                Senior Sound Designer and Technical Audio Engineer<br />
                Credits: King of Meat (Amazon Games), Factorio, Wargaming
              </p>
              <p className="text-gray-300 leading-relaxed" style={{ whiteSpace: 'pre-line' }}>
                {`For me, audio is far more than just a job. It is a passion driven by a constant search for the most efficient technical solutions and the most expressive sonic design. I believe that sound and music are the ultimate tools for player immersion because they bypass the filters of language and symbols, striking directly at the subconscious to evoke immediate emotion and instinct.

For over 10 years, I have been bridging the gap between creative sound art and technical implementation across PC, console, and mobile games. I specialize in building robust, adaptive, and performance-aware audio frameworks using Wwise, FMOD, and Unreal Engine.

I do not just create sounds; I design how they behave. From asset optimization to writing complex event-driven logic alongside programmers, my goal is always to maximize the impact of audio communication with the player while ensuring flawless technical execution.

With a background spanning TV post-production, electronic music, and 250+ field recording trips, I bring an old-school obsession with pristine audio quality into modern, systemic game development.`}
              </p>
            </div>
          </section>
        ) : (
          <>
            {SECTIONS.map(sec => (
              <section key={sec.id} id={sec.id} className="min-h-screen flex items-center">
                <div className="p-8 max-w-7xl mx-auto w-full">
                  <h2 className="text-3xl font-bold mb-4 text-white">{sec.label}</h2>
                  <p className="text-gray-300 text-lg leading-relaxed mb-8 max-w-3xl">{sec.intro}</p>
                  <div className="grid md:grid-cols-2 gap-8">
                    {sec.videos.map((v, i) => (
                      <VideoCard
                        key={i}
                        {...v}
                        isActive={activeVideo === v.video}
                        onPlay={() => playVideo(v.video)}
                        playerRef={playerRef}
                      />
                    ))}
                  </div>
                </div>
              </section>
            ))}
          </>
        )}
      </main>
    </div>
  );
}   
